### PR TITLE
:bug:  Correctly calculate total balance from transactions

### LINKED ISSUE #31: Fix -0,00€ bug

### PR DESCRIPTION
**Pull request by Importantus**
The total balance for a user within a group is now correctly calculated by summing up the pre-calculated transactions.

This change also handles cases where a local user might not be chosen (`me` is null)

### CODE REVIEW

File: app/src/main/java/digital/fischers/coinsaw/ui/home/HomeScreen.kt [hunk 1]
```diff
@@ -58,7 +57,9 @@ fun HomeScreen(
             Column {
                 Text(
                     text = stringResource(id = R.string.screen_title_groups), style = TextStyle(
-                        fontSize = 24.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.neutral
+                        fontSize = 24.sp,
+                        fontWeight = FontWeight.Bold,
+                        color = MaterialTheme.colorScheme.neutral
```
Comment (hoppjan) [inline app/src/main/java/digital/fischers/coinsaw/ui/home/HomeScreen.kt]: Reformat?

**Review by hoppjan — APPROVED** [review]
Some of this seems to be reformatting, but other than that, it looks fine 👍 ✨ 🐢
